# Generated by Django 3.0.3 on 2020-02-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='body',
        ),
        migrations.AddField(
            model_name='messages',
            name='message',
            field=models.CharField(default='qweqweqw', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messages',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
